service: aws-node-http-api-project
frameworkVersion: '3'

# for production I would add stages here to deploy to dev/test/prod for example 

provider:
  name: aws
  runtime: nodejs18.x
  region: 'eu-west-2'
  iam:
    role:
      statements:
        # Allow function to read/write objects in a bucket, chose this over ORM as it's easier to demonstrate least permissions & knowledge of IAM
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::invidibility-score-bucket/*'

functions:
  invisibilityScore:
    handler: src/invisibilityScore.handler
    events:
      - httpApi:
          path: /
          method: post

resources:
  Resources:
    invisibilityScoreBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: invisibility-score-bucket
        OwnershipControls:
          Rules:
           - ObjectOwnership: BucketOwnerPreferred
	

